// Code generated by go-router for HTTP request parsing. ADD YOUR BUSINESS RULE HERE.
// Request  Type: structs.RequestStruct
// Generated File: /home/guionardo/dev/go-router/cmd/endpoint_gen/structs/structs_process.go
// Response Type: structs.ResponseStruct

package structs

import "net/http"

func (h *RequestStruct) Process(r *http.Request) (ResponseStruct, error) {
	// TODO: Add your business rule here
	return ResponseStruct{}, nil
}
