// Code generated by go-router for HTTP request parsing. DO NOT EDIT.
// Request  Type: structs.RequestStruct
// Generated File: /home/guionardo/dev/go-router/cmd/endpoint_gen/structs/structs_parser.go
// Response Type: structs.ResponseStruct

package structs

import (
	"github.com/guionardo/go-router/pkg/tools"
	"github.com/guionardo/go-router/router"
	"io"
	"net/http"
)

func (h *RequestStruct) ParseRequest(r *http.Request) error {
	if err := h.ParseBody(r); err != nil {
		return err
	}

	if err := tools.GroupError("path",
		func() error { return tools.ParseInt("Id", r.PathValue("id"), &h.Id) },
		func() error { return tools.ParseUInt("Operation", r.PathValue("operation"), &h.Operation) },
	); err != nil {
		return err
	}

	if err := tools.GroupError("headers",
		func() error {
			h.APIKey = r.Header.Get("X-API-KEY")
			return nil
		},
		func() error { return tools.ParseDuration("TTL", r.Header.Get("X-TTL"), &h.TTL) },
		func() error { return tools.ParseFloat64("Value", r.Header.Get("value"), &h.Value) },
		func() error { return tools.ParseUInt8("NumberByte", r.Header.Get("number_byte"), &h.NumberByte) },
	); err != nil {
		return err
	}

	if err := tools.GroupError("query",
		func() error {
			h.Name = r.URL.Query().Get("name")
			return nil
		},
		func() error { return tools.ParseTime("When", r.URL.Query().Get("when"), &h.When) },
		func() error { return tools.ParseBool("Enabled", r.URL.Query().Get("enabled"), &h.Enabled) },
		func() error { return tools.ParseUInt64("NumberBig", r.URL.Query().Get("number_big"), &h.NumberBig) },
	); err != nil {
		return err
	}
	// Validation (native)
	if err := h.Validate(); err != nil {
		return err
	}
	return nil
}
func (h *RequestStruct) ParseBody(r *http.Request) (err error) {
	body, err := io.ReadAll(r.Body)
	if err == nil {
		h.BodyField = body
	}
	return err
}

func (h *RequestStruct) Handle(w http.ResponseWriter, r *http.Request) {
	var (
		response any
		err      error
	)
	if err = h.ParseRequest(r); err == nil {
		response, err = h.Process(r)
	}
	router.Handle(w, response, err)
}

// Hash validation for type
func init() {
	tools.ValidateHash[RequestStruct](0x97e91a24ae818810)
}
