//SIGNATURE:2a27d2c2
// Code generated by go-router for HTTP request parsing. ADD YOUR BUSINESS RULE HERE.
// Request  Type: structs.RequestStruct
// Response Type: structs.ResponseStruct

package structs

import "net/http"

// Process(r *http.Request) (ResponseStruct, error) TODO: Add your bussines rule here
func (h *RequestStruct) Process(r *http.Request) (ResponseStruct, error) {
	return ResponseStruct{}, nil
}
