repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files

    - repo: https://github.com/tekwizely/pre-commit-golang
      rev: master # Or a specific tag/commit hash for stability
      hooks:
          - id: go-mod-tidy
        #   - id: golangci-lint # 1.24 - does not have version for 1.25
          - id: go-test-mod # This hook runs `go test` for the current module
            args: ["-v"] # Optional: Add arguments to `go test`, e.g., for verbose output

    - repo: https://github.com/guionardo/govuln
      rev: v0.1.0
      hooks:
          - id: go-vulncheck
