package generator

// https://github.com/mailru/easyjson
import (
	"fmt"
	"io"
	"os"
	"reflect"
	"strings"

	"github.com/guionardo/go-router/pkg/attributor"
	"github.com/guionardo/go-router/pkg/code"
	"github.com/guionardo/go-router/pkg/generator/parsers"
	"github.com/guionardo/go-router/pkg/outputs"
	reflections "github.com/guionardo/go-router/pkg/reflect"
	"github.com/guionardo/go-router/pkg/tools"
	"github.com/guionardo/go-router/router"
	"github.com/guionardo/go/pkg/set"
	"github.com/mailru/easyjson"
)

type (
	mu interface {
		easyjson.MarshalerUnmarshaler
	}
	Generator[T mu, R mu] struct {
		tReq, tRes     reflect.Type
		imports        set.Set[string] // alias:path
		moduleName     string
		projectRoot    string
		attr           attributor.Attributor
		hasValidations bool
		outputFiles    *outputs.Outputs[T, R]
		bodyParser     *parsers.Body[T]
	}
)

func New[T mu, R mu]() *Generator[T, R] {
	tType := reflections.New[T]()
	g := &Generator[T, R]{
		imports:     set.New[string](),
		attr:        attributor.New[T](),
		outputFiles: outputs.New[T, R](),
		projectRoot: tType.ProjectRootFolder,
		moduleName:  tType.ModuleName,
	}

	g.tReq = g.addType(reflect.TypeFor[T]())
	g.tRes = g.addType(reflect.TypeFor[R]())

	pathParser := parsers.NewPath[T]()
	queryParser := parsers.NewQuery[T]()
	headerParser := parsers.NewHeader[T]()
	g.bodyParser = parsers.NewBody[T]()
	validatorParser := parsers.NewValidators[T]()

	g.hasValidations = validatorParser.HasValidations

	g.imports.AddMultiple("net/http", tools.ToolsImport, router.RouterImport)
	g.imports.UpdateFrom(pathParser.Imports)
	g.imports.UpdateFrom(queryParser.Imports)
	g.imports.UpdateFrom(headerParser.Imports)
	g.imports.UpdateFrom(validatorParser.Imports)
	g.imports.UpdateFrom(g.bodyParser.Imports)

	return g
}

func (g *Generator[T, R]) addType(t reflect.Type) reflect.Type {
	tType := reflections.NewFromType[T](t)
	if tType.Error != nil {
		panic(tType.Error)
	}

	return tType.Type
}

func (g *Generator[T, R]) Generate() (err error) {
	// parser

	if err = g.generateParser(); err != nil {
		return err
	}

	// ProcessFile

	if err = g.generateProcess(); err == nil {
		_ = outputs.SignFile(g.outputFiles.ProcessFile)
	}

	return err

}

func (g *Generator[T, R]) generateParser() error {
	c := code.New(g.outputFiles.PackageName, g.outputFiles.ParseRequestFile)
	c.AddHeader("Code generated by go-router for HTTP request parsing. DO NOT EDIT.",
		fmt.Sprintf("Request  Type: %s", g.tReq.String()),
		fmt.Sprintf("Response Type: %s\n", g.tRes.String()))

	c.AddImports(g.imports.ToArray()...)
	err := g.writeParserCode(c)
	if err == nil {
		g.writeParserBodyFuncCode(c)
		g.writeHandlerCode(c)
		g.writeInitCode(c)
		err = c.Write()
	}

	return err
}

func (g *Generator[T, R]) generateProcess() (err error) {
	if len(g.outputFiles.ProcessFile) == 0 {
		return nil
	}

	c := code.New(g.outputFiles.PackageName, g.outputFiles.ProcessFile)
	c.AddHeader("Code generated by go-router for HTTP request parsing. ADD YOUR BUSINESS RULE HERE.",
		fmt.Sprintf("Request  Type: %s", g.tReq.String()),
		fmt.Sprintf("Response Type: %s\n", g.tRes.String()))

	c.AddImports("net/http")
	g.writeProcessCode(c)
	return c.Write()
}

func (g *Generator[T, R]) writeInitCode(c *code.Code) {
	c.AddFunc("", "init()", fmt.Sprintf("tools.ValidateHash[%s](0x%x)", g.tReq.Name(), tools.TypeHash(g.tReq)), "Hash validation for type")
}

func (g *Generator[T, R]) writeParserCode(c *code.Code) error {
	body := []string{
		g.getParserForBody(),
		g.getParserForPath(),
		g.getParserForHeaders(),
		g.getParserForQuery(),
		g.getValidation(),
		"return nil",
	}

	c.AddFunc(fmt.Sprintf("h *%s", g.tReq.Name()), "ParseRequest(r *http.Request) error", strings.Join(body, "\n"), "")
	return nil
}

func (g *Generator[T, R]) writeProcessCode(c *code.Code) {
	c.AddFunc(fmt.Sprintf("h *%s", g.tReq.Name()),
		fmt.Sprintf("Process(r *http.Request) (%s, error)", g.tRes.Name()),
		fmt.Sprintf("return %s{},nil", g.tRes.Name()),
		"TODO: Add your bussines rule here")
}

func (g *Generator[T, R]) writeHandlerCode(c *code.Code) {
	c.AddFunc(fmt.Sprintf("h *%s", g.tReq.Name()), "Handle(w http.ResponseWriter, r *http.Request)",
		`
	var (
		response any
		err      error
	)
	if err = h.ParseRequest(r); err == nil {
		response, err = h.Process(r)
	}
	router.Handle(w, response, err)
	`, "")
}

func (g *Generator[T, R]) writeParserBodyFuncCode(c *code.Code) {
	if bodyFunc := g.bodyParser.ParseBodyFunc(); len(bodyFunc) > 0 {
		c.AddRaw(bodyFunc)
	}
}

func (g *Generator[T, R]) getParserForBody() string {
	if len(g.bodyParser.ParseBodyFunc()) > 0 {
		return "if err:=h.ParseBody(r); err!=nil {return err}\n"
	}
	return ""
}

func (g *Generator[T, R]) getParserForPath() string {
	attributions := make([]string, 0)
	for field, tagValue := range getFieldsByTag(g.tReq, "path") {
		attributions = append(attributions, g.attr.Create(field, "h", `r.PathValue("%s")`, tagValue))
	}
	if len(attributions) == 0 {
		return ""
	}
	return fmt.Sprintf("if err:=tools.GroupError(\"path\",%s,); err!=nil { return err }\n",
		strings.Join(attributions, ",\n"))
}

func (g *Generator[T, R]) getParserForHeaders() string {
	attributions := make([]string, 0)
	for field, tagValue := range getFieldsByTag(g.tReq, "header") {
		attributions = append(attributions, g.attr.Create(field, "h", `r.Header.Get("%s")`, tagValue))
	}
	if len(attributions) == 0 {
		return ""
	}
	return fmt.Sprintf("if err:=tools.GroupError(\"headers\",%s,); err!=nil { return err }\n",
		strings.Join(attributions, ",\n"))
}

func (g *Generator[T, R]) getParserForQuery() string {
	attributions := make([]string, 0)
	for field, tagValue := range getFieldsByTag(g.tReq, "query") {
		attributions = append(attributions, g.attr.Create(field, "h", `r.URL.Query().Get("%s")`, tagValue))
	}
	if len(attributions) == 0 {
		return ""
	}
	return fmt.Sprintf("if err:=tools.GroupError(\"query\",%s,); err!=nil { return err }\n",
		strings.Join(attributions, ",\n"))
}

func (g *Generator[T, R]) getValidation() string {
	if !g.hasValidations {
		return ""
	}
	if reflect.TypeFor[T]().Implements(reflect.TypeFor[parsers.Validator]()) {
		return "// Validation (native)\nif err:=h.Validate();err!=nil{ return err}\n"
	}
	if reflect.TypeFor[T]().Implements(reflect.TypeFor[parsers.ValidatorGetter]()) {
		return "// Validation with custom validator\nvalidate := h.GetValidator()\nif err:=validate.Struct(h);err!=nil{return err}\n"
	}

	return "// Validation with default validator\nvalidate := validator.New(validator.WithRequiredStructEnabled())\nif err:=validate.Struct(h);err!=nil{return err}\n"
}

// GetWriter returns a NewFormatWriter for the fileName.
func (g *Generator[T, R]) GetWriter(fileName string) (fw io.WriteCloser, err error) {
	w, err := os.Create(fileName)
	if err != nil {
		return nil, err
	}
	return code.NewFormatWriter(w, fileName), nil
}
